### ISSUE TITLE
太强了

### ISSUE THREAD

**Issue by rongtongxueya** [zhaoyutim/TS-SatFire#1]
hhh哥你的工作太及时了，太棒了，刚好我的硕士课题就是加州火灾的预测hhhh，完全靠你了哥hhhhh

**Comment by zhaoyutim** [comment]
hhh欢迎合作以及使用我们的数据集https://www.kaggle.com/datasets/z789456sx/ts-satfire

**Comment by rongtongxueya** [comment]
hhhhhhh必须用上，哥要不加个联系方式，师兄可以指导一下我工作

**Comment by zhaoyutim** [comment]
把联系方式发我邮件吧，这个issue我就关掉了

**Comment by zhaoyutim** [comment]
> hhhhhhh必须用上，哥要不加个联系方式，师兄可以指导一下我工作

Hello, 有给我发邮件嘛？可以在我首页找到的zhaoyutim@gmail.com
