### ISSUE TITLE
Dataset Google Drive link is not working

### ISSUE THREAD

**Issue by ruzcko** [zhaoyutim/TS-SatFire#2]
![image](https://github.com/user-attachments/assets/0970e00b-fb6a-4020-9644-85ec5a701112)

The dataset link provided in the readme file is not working.

**Comment by zhaoyutim** [comment]
Thanks for your comment! I will fix the link to use the kaggle link instead. You can find the dataset here: https://www.kaggle.com/datasets/z789456sx/ts-satfire
